spring:
  application:
    name: Kioke Journal Service

rabbitmq:
  queue:
    name: journals.created
  exchange:
    name: journals
  routing:
    key: journals.created

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

