spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/journaldb
    username: kioke
    password: password

  rabbitmq:
    host: localhost
    port: 5672
    username: kioke
    password: password

  devtools:
    restart:
      enabled: true

postgres:
  user: kioke
  password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${SERVICE_DISCOVERY_PORT}/eureka

kioke:
  mock:
    data-generator:
      enabled: false

logging:
  level:
    kioke: DEBUG
