server:
  port: ${JOURNAL_SERVICE_PORT}

spring:
  application:
    name: journal

eureka:
  instance:
    appname: journal
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    jmx:
      exposure:
        include: health, info, prometheus, metrics
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus, metrics

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

rabbitmq:
  queue:
    user-registration:
      name: user.registration.journal

springdoc:
  api-docs:
    path: /v3/api-docs/journal

  swagger-ui:
    enabled: false

logging:
  level:
    kioke: DEBUG
