server:
  port: ${USER_SERVICE_PORT}

spring:
  application:
    name: user

eureka:
  instance:
    appname: user
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true

rabbitmq:
  queue:
    user-registration:
      name: user.registration.user

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
