spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: kioke
    password: password

  rabbitmq:
    host: localhost
    port: 5672
    username: kioke
    password: password

  devtools:
    restart:
      enabled: true

postgres:
  user: kioke
  password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${SERVICE_DISCOVERY_PORT}/eureka

springdoc:
  swagger-ui:
    enabled: true
    path: /user-service/swagger-ui.html
  api-docs:
    enabled: true
    path: /user-service/api-docs
